version: '3.8'

services:
  bot:
    build: .
    container_name: my_bot_container
    restart: always
    volumes:
      - .:/LLAF  # Монтируем текущую директорию в контейнер
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
